const contacts=[];
const labels={online:'Disponible',away:'Ausente',busy:'Ocupado',offline:'Desconectado'};
const nicks=['xX_Spencer_Xx','[S]pencer™','Spencer says: hola!','-=Neo2005=-','★ Spencer ★','♥•.¸¸.• Spencer •.¸¸.•♥','×º°”˜`”°º× Spencer ×º°”˜`”°º×','★彡 Spencer 彡★','♫ S P E N C E R ♫','ღ Spencer ღ'];
let active=null,toastTimer,soundOn=true,audioCtx;
const $=s=>document.querySelector(s);
const e={name:$('#displayName'),personal:$('#personalMessage'),status:$('#statusSelect'),selfDot:$('#selfStatusDot'),random:$('#randomNickBtn'),next:$('#newChatBtn'),search:$('#contactSearch'),list:$('#contactList'),counter:$('#onlineCounter'),offline:$('#offlineCounter'),chat:$('#chatWindow'),title:$('#chatTitle'),dot:$('#chatStatusDot'),info:$('#chatInfoName'),avatar:$('#chatAvatar'),pane:$('#messagePane'),form:$('#messageForm'),input:$('#messageInput'),nudge:$('#nudgeBtn'),sound:$('#soundToggle'),toast:$('#toast')};
const key=id=>`messenger-revival:conversation:${id}`;
function get(id){if(!id)return[];try{return JSON.parse(localStorage.getItem(key(id)))||[]}catch{return[]}}
function save(id,m){if(id)localStorage.setItem(key(id),JSON.stringify(m.slice(-100)))}
function contact(){return contacts.find(c=>c.id===active)||null}
function renderContacts(q=''){if(!e.list)return;e.list.innerHTML='';const filtered=contacts.filter(c=>(c.name+(c.mood||'')).toLowerCase().includes(q.toLowerCase()));filtered.forEach(c=>{const li=document.createElement('li');li.className=`contact-item${c.id===active?' active':''}`;li.innerHTML=`<span class="person-icon ${c.status}">●</span><div class="contact-copy"><strong></strong><small></small></div>`;li.querySelector('strong').textContent=c.name;li.querySelector('small').textContent=c.mood||'';li.onclick=()=>open(c.id);e.list.appendChild(li)});if(e.counter)e.counter.textContent=String(contacts.filter(c=>c.status==='online').length);if(e.offline)e.offline.textContent=String(contacts.filter(c=>c.status==='offline').length)}
function render(){const c=contact();if(!c||!e.pane)return;e.pane.innerHTML='';get(active).forEach(m=>{const w=document.createElement('div');w.className=`message ${m.sender==='me'?'mine':''}`;w.innerHTML='<div class="message-meta"></div><div class="message-bubble"></div>';w.querySelector('.message-meta').textContent=`${m.sender==='me'?(e.name?.value||'Tú'):c.name} ... dice:`;const bubble=w.querySelector('.message-bubble');bubble.textContent=m.text;if(m.format)Object.assign(bubble.style,m.format);e.pane.appendChild(w)});e.pane.scrollTop=e.pane.scrollHeight}
function open(id){const c=contacts.find(x=>x.id===id);if(!c)return;active=id;if(e.chat)e.chat.style.display='';if(e.title)e.title.textContent=c.name;if(e.info)e.info.textContent=c.name;if(e.dot)e.dot.className=`person-icon ${c.status}`;renderContacts(e.search?.value||'');render();e.input?.focus()}
function append(sender,text,format){if(!active)return;const m=get(active);m.push({sender,text,time:Date.now(),...(format?{format}:{})});save(active,m);render()}
function toast(t){clearTimeout(toastTimer);if(!e.toast)return;e.toast.textContent=t;e.toast.classList.add('show');toastTimer=setTimeout(()=>e.toast.classList.remove('show'),1900)}
async function unlockAudio(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')await audioCtx.resume();return audioCtx.state==='running'}catch{return false}}
async function playNudge(){if(!soundOn)return;if(!await unlockAudio())return;const t=audioCtx.currentTime;[0,.09,.18,.27].forEach((d,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=i%2?'square':'sawtooth';o.frequency.setValueAtTime(i%2?230:310,t+d);g.gain.setValueAtTime(.1,t+d);g.gain.exponentialRampToValueAtTime(.0001,t+d+.08);o.connect(g);g.connect(audioCtx.destination);o.start(t+d);o.stop(t+d+.085)})}
function nudge(){if(!active)return; e.chat?.classList.remove('nudging');void e.chat?.offsetWidth;e.chat?.classList.add('nudging');playNudge();toast('⚡ ¡Zumbido enviado!')}
if(e.form)e.form.onsubmit=ev=>{ev.preventDefault();if(!active)return;const t=e.input.value.trim();if(!t)return;const cs=getComputedStyle(e.input),format={fontFamily:e.input.style.fontFamily||cs.fontFamily,fontSize:e.input.style.fontSize||cs.fontSize,color:e.input.style.color||cs.color,fontWeight:e.input.style.fontWeight||cs.fontWeight,fontStyle:e.input.style.fontStyle||cs.fontStyle,textDecoration:e.input.style.textDecoration||cs.textDecorationLine};append('me',t,format);e.input.value=''};
if(e.input)e.input.onkeydown=ev=>{if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();e.form?.requestSubmit()}};
document.querySelectorAll('.emoji-btn').forEach(b=>b.onclick=()=>{if(e.input){e.input.value+=b.dataset.emoji||'';e.input.focus()}});if(e.nudge)e.nudge.onclick=nudge;if(e.sound)e.sound.onclick=()=>{soundOn=!soundOn;e.sound.textContent=soundOn?'🔊':'🔇'};document.addEventListener('pointerdown',unlockAudio,{once:true});
if(e.status)e.status.onchange=()=>{if(e.selfDot)e.selfDot.className=`person-icon ${e.status.value}`;localStorage.setItem('messenger-revival:self-status',e.status.value)};
if(e.name)e.name.onchange=()=>localStorage.setItem('messenger-revival:nick',e.name.value);
if(e.personal){e.personal.value=localStorage.getItem('messenger-revival:personal-message')||'';const savePersonal=()=>{const value=e.personal.value.slice(0,129);e.personal.value=value;localStorage.setItem('messenger-revival:personal-message',value);window.dispatchEvent(new CustomEvent('messenger-revival:personal-message-changed',{detail:{message:value}}))};e.personal.addEventListener('input',savePersonal);e.personal.addEventListener('change',savePersonal)}
if(e.random)e.random.onclick=()=>{e.name.value=nicks[Math.floor(Math.random()*nicks.length)];localStorage.setItem('messenger-revival:nick',e.name.value);toast('Apodo actualizado al estilo 2005 ツ')};if(e.next)e.next.onclick=()=>toast('Agregar contacto estará conectado a usuarios reales.');if(e.search)e.search.oninput=ev=>renderContacts(ev.target.value);
const displayPictures=[{id:'daisy',name:'Orange Daisy'},{id:'soccer',name:'Soccer Ball'},{id:'chess',name:'Chess Pieces'},{id:'beach',name:'Beach Chairs'},{id:'rocket',name:'Rocket Launch'},{id:'duck',name:'Rubber Ducky'},{id:'dog',name:'Friendly Dog'},{id:'dirt',name:'Dirt Bike'}];let pendingDP=localStorage.getItem('messenger-revival:display-picture')||'default',customDP=localStorage.getItem('messenger-revival:custom-picture')||'',pendingHidden=localStorage.getItem('messenger-revival:hide-picture')==='1';const dlg=$('#displayPictureDialog'),list=$('#dpList'),preview=$('#dpPreview'),hideDP=$('#hideDisplayPicture');
function artMarkup(id){if(id==='none')return '<span class="dp-art none"></span>';if(id==='default')return '<span class="classic-avatar hero"><i></i><b></b><em></em></span>';if(id==='custom'&&customDP)return `<img src="${customDP}" alt="Custom" style="width:100%;height:100%;object-fit:cover">`;const p=displayPictures.find(x=>x.id===id);return `<span class="dp-art ${p?.id||'none'}"></span>`}
function renderDPList(){if(!list)return;list.innerHTML='';[{id:'default',name:'Default Messenger'},...displayPictures].forEach(p=>{const row=document.createElement('div');row.className=`dp-item${pendingDP===p.id&&!pendingHidden?' selected':''}`;row.innerHTML=`<span class="dp-thumb">${artMarkup(p.id)}</span><span>${p.name}</span>`;row.onclick=()=>{pendingDP=p.id;pendingHidden=false;if(hideDP)hideDP.checked=false;renderDPList();renderPreview()};list.appendChild(row)})}
function renderPreview(){if(preview)preview.innerHTML=artMarkup(pendingHidden?'none':pendingDP)}function openDP(){pendingDP=localStorage.getItem('messenger-revival:display-picture')||'default';pendingHidden=localStorage.getItem('messenger-revival:hide-picture')==='1';if(hideDP)hideDP.checked=pendingHidden;renderDPList();renderPreview();if(dlg)dlg.hidden=false}function closeDP(){if(dlg)dlg.hidden=true}
function paintSelf(){const saved=localStorage.getItem('messenger-revival:display-picture')||'default',hidden=localStorage.getItem('messenger-revival:hide-picture')==='1',html=artMarkup(hidden?'none':saved);['selfAvatar','selfAvatarChat'].forEach(id=>{const a=document.getElementById(id);if(a)a.innerHTML=html})}
function applyDP(){localStorage.setItem('messenger-revival:display-picture',pendingDP);localStorage.setItem('messenger-revival:hide-picture',pendingHidden?'1':'0');paintSelf();closeDP();toast('Imagen para mostrar actualizada')}
$('#openDisplayPictures')?.addEventListener('click',openDP);$('#openDisplayPicturesChat')?.addEventListener('click',openDP);$('#closeDisplayPictures')?.addEventListener('click',closeDP);$('#dpCancel')?.addEventListener('click',closeDP);$('#dpOk')?.addEventListener('click',applyDP);if(hideDP)hideDP.onchange=()=>{pendingHidden=hideDP.checked;renderPreview()};$('#browsePicture')?.addEventListener('click',()=>{const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=()=>{const f=i.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{customDP=String(r.result);localStorage.setItem('messenger-revival:custom-picture',customDP);pendingDP='custom';pendingHidden=false;renderPreview()};r.readAsDataURL(f)};i.click()});
function draggable(win){const h=win.querySelector('.drag-handle');if(!h)return;let sx,sy,sl,st,down=false;h.addEventListener('mousedown',ev=>{if(ev.target.tagName==='BUTTON')return;down=true;sx=ev.clientX;sy=ev.clientY;sl=win.offsetLeft;st=win.offsetTop});window.addEventListener('mousemove',ev=>{if(down){win.style.left=Math.max(0,sl+ev.clientX-sx)+'px';win.style.top=Math.max(0,st+ev.clientY-sy)+'px'}});window.addEventListener('mouseup',()=>down=false)}document.querySelectorAll('.msn-window').forEach(draggable);
const sn=localStorage.getItem('messenger-revival:nick'),ss=localStorage.getItem('messenger-revival:self-status');if(sn&&e.name)e.name.value=sn;if(ss&&labels[ss]&&e.status){e.status.value=ss;if(e.selfDot)e.selfDot.className=`person-icon ${ss}`}renderContacts();paintSelf();if(e.chat)e.chat.style.display='none';