(()=>{
const $=s=>document.querySelector(s),cfg=window.MESSENGER_SUPABASE||{},shell=$('#authShell'),win=$('#authWindow'),loginView=$('#authLoginView'),registerView=$('#authRegisterView'),stage=$('.stage');
const loginEmail=$('#authEmail'),loginPassword=$('#authPassword'),loginStatus=$('#authPresence'),rememberMe=$('#authRememberMe'),autoSignIn=$('#authAutoSignIn'),loginMessage=$('#authLoginMessage'),rememberedName=$('#authRememberedName'),rememberedImage=$('#authRememberedImage'),switchUser=$('#authSwitchUser');
const regEmail=$('#registerEmail'),regName=$('#registerDisplayName'),regPassword=$('#registerPassword'),regConfirm=$('#registerPasswordConfirm'),regMessage=$('#registerMessage'),regPreview=$('#registerPhotoPreview'),regFile=$('#registerPhotoFile');
const REMEMBERED='messenger-revival:remembered-account',AUTO='messenger-revival:auto-sign-in',PENDING='messenger-revival:pending-registration:';let pendingPhoto=null,client=null,currentProfile=null;
if(cfg.url&&cfg.publishableKey&&window.supabase?.createClient)client=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
window.MessengerSession={client,user:null,profile:null,get userId(){return this.user?.id||'guest'},scopedKey(n){return `messenger-revival:user:${this.userId}:${n}`}};
function msg(el,t,type=''){if(el){el.textContent=t;el.className='auth-status'+(type?' '+type:'')}}function remembered(){try{return JSON.parse(localStorage.getItem(REMEMBERED)||'null')}catch{return null}}
function setRememberedVisual(r){if(!r){rememberedName.textContent='';rememberedImage.hidden=true;rememberedImage.removeAttribute('src');$('#authDefaultAvatar').hidden=false;if(switchUser)switchUser.hidden=true;return}loginEmail.value=r.email||'';rememberedName.textContent=r.display_name||r.email||'';if(switchUser)switchUser.hidden=false;if(r.display_picture){rememberedImage.src=r.display_picture+(r.display_picture.includes('?')?'&':'?')+'v='+Date.now();rememberedImage.hidden=false;$('#authDefaultAvatar').hidden=true}else{rememberedImage.removeAttribute('src');rememberedImage.hidden=true;$('#authDefaultAvatar').hidden=false}}
async function refreshRemembered(){const r=remembered();setRememberedVisual(r);if(!r||!client)return;try{const {data:{session}}=await client.auth.getSession();if(!session?.user||session.user.email?.toLowerCase()!==String(r.email||'').toLowerCase())return;const {data:p}=await client.from('profiles').select('display_name,display_picture').eq('id',session.user.id).single();if(!p)return;const fresh={...r,display_name:p.display_name||r.display_name,display_picture:p.display_picture||r.display_picture||''};localStorage.setItem(REMEMBERED,JSON.stringify(fresh));setRememberedVisual(fresh)}catch{}}
function paintRemembered(){setRememberedVisual(remembered())}
function showLogin(){registerView.hidden=true;loginView.hidden=false;refreshRemembered()}function showRegister(){loginView.hidden=true;registerView.hidden=false}
async function getProfile(u){const {data,error}=await client.from('profiles').select('*').eq('id',u.id).single();if(error)throw error;return data}
async function uploadBlob(u,dataUrl){if(!dataUrl)return'';const blob=await fetch(dataUrl).then(r=>r.blob()),ext=(blob.type.split('/')[1]||'png').replace('jpeg','jpg'),path=`${u.id}/display-picture.${ext}`;const {error}=await client.storage.from(cfg.displayPicturesBucket||'display-pictures').upload(path,blob,{upsert:true,contentType:blob.type});if(error)throw error;return client.storage.from(cfg.displayPicturesBucket||'display-pictures').getPublicUrl(path).data.publicUrl||''}
async function finalizePending(u,p){let raw='';try{raw=localStorage.getItem(PENDING+u.email.toLowerCase())||''}catch{}if(!raw)return p;const photo=await uploadBlob(u,raw);if(photo){await client.from('profiles').update({display_picture:photo,updated_at:new Date().toISOString()}).eq('id',u.id);p.display_picture=photo}localStorage.removeItem(PENDING+u.email.toLowerCase());return p}
function apply(p){localStorage.setItem('messenger-revival:nick',p.display_name||'Messenger User');localStorage.setItem('messenger-revival:personal-message',p.personal_message||'');localStorage.setItem('messenger-revival:self-status',p.status||'online');const picture=p.display_picture||'',pictureKey=window.MessengerSession.scopedKey('custom-picture'),selectionKey=window.MessengerSession.scopedKey('display-picture');if(picture){localStorage.setItem('messenger-revival:custom-picture',picture);localStorage.setItem('messenger-revival:display-picture','custom');localStorage.setItem('messenger-revival:hide-picture','0');localStorage.setItem(pictureKey,picture);localStorage.setItem(selectionKey,'custom')}else{localStorage.removeItem('messenger-revival:custom-picture');localStorage.removeItem('messenger-revival:display-picture');localStorage.removeItem(pictureKey);localStorage.removeItem(selectionKey)}if($('#displayName'))$('#displayName').value=p.display_name||'';if($('#personalMessage'))$('#personalMessage').value=p.personal_message||'';if($('#statusSelect'))$('#statusSelect').value=p.status||'online';if(window.MessengerProfileSync?.paint)window.MessengerProfileSync.paint(picture);else ['#selfAvatar','#selfAvatarChat'].forEach(s=>{const h=$(s);if(h)h.innerHTML=picture?`<img class="profile-avatar-image" src="${picture}" alt="Display picture">`:'<span class="classic-avatar self"><i></i><b></b><em></em></span>'})}
async function enter(u,p){p=await finalizePending(u,p||await getProfile(u));currentProfile=p;window.MessengerSession.user=u;window.MessengerSession.profile=p;apply(p);if(rememberMe?.checked)localStorage.setItem(REMEMBERED,JSON.stringify({email:u.email,display_name:p.display_name,display_picture:p.display_picture||''}));else localStorage.removeItem(REMEMBERED);localStorage.setItem(AUTO,autoSignIn?.checked?'1':'0');shell.hidden=true;stage?.classList.remove('auth-hidden');document.body.classList.remove('auth-locked');window.dispatchEvent(new CustomEvent('messenger-revival:auth-ready',{detail:{user:u,profile:p}}))}
async function signIn(){if(!client)return;win.classList.add('busy');try{const {data,error}=await client.auth.signInWithPassword({email:loginEmail.value.trim(),password:loginPassword.value});if(error)throw error;let p=await getProfile(data.user);await client.from('profiles').update({status:loginStatus.value,updated_at:new Date().toISOString()}).eq('id',data.user.id);p.status=loginStatus.value;await enter(data.user,p)}catch(e){msg(loginMessage,e.message||'No fue posible iniciar sesión.','error')}finally{win.classList.remove('busy')}}
async function register(){const email=regEmail.value.trim(),name=regName.value.trim(),password=regPassword.value;if(!email||!name||!password)return msg(regMessage,'Completa correo, nombre y contraseña.','error');if(password!==regConfirm.value)return msg(regMessage,'Las contraseñas no coinciden.','error');if(password.length<8)return msg(regMessage,'Usa una contraseña de al menos 8 caracteres.','error');win.classList.add('busy');try{if(pendingPhoto){const r=new FileReader();const dataUrl=await new Promise((res,rej)=>{r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(pendingPhoto)});localStorage.setItem(PENDING+email.toLowerCase(),dataUrl)}const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)throw error;loginEmail.value=email;if(data.session&&data.user)await enter(data.user,await getProfile(data.user));else{showLogin();msg(loginMessage,'Cuenta creada. Confirma el correo y luego inicia sesión; tu imagen se guardará al primer ingreso.','ok')}}catch(e){msg(regMessage,e.message||'No fue posible crear la cuenta.','error')}finally{win.classList.remove('busy')}}
async function signOut(){try{await client?.auth.signOut({scope:'local'})}catch{}window.MessengerSession.user=null;window.MessengerSession.profile=null;currentProfile=null;window.dispatchEvent(new CustomEvent('messenger-revival:auth-signed-out'));localStorage.setItem(AUTO,'0');if(autoSignIn)autoSignIn.checked=false;stage?.classList.add('auth-hidden');document.body.classList.add('auth-locked');shell.hidden=false;if(loginPassword)loginPassword.value='';showLogin();msg(loginMessage,'Sesión cerrada.','ok')}
async function changeUser(){try{await client?.auth.signOut({scope:'local'})}catch{}localStorage.removeItem(REMEMBERED);localStorage.setItem(AUTO,'0');window.MessengerSession.user=null;window.MessengerSession.profile=null;currentProfile=null;window.dispatchEvent(new CustomEvent('messenger-revival:auth-signed-out'));if(rememberMe)rememberMe.checked=false;if(autoSignIn)autoSignIn.checked=false;if(loginEmail)loginEmail.value='';if(loginPassword)loginPassword.value='';setRememberedVisual(null);msg(loginMessage,'Escribe los datos de otra cuenta.','ok')}
window.MessengerAuth={signOut,changeUser,client,get profile(){return currentProfile}};$('#authSignIn')?.addEventListener('click',signIn);$('#authOpenRegister')?.addEventListener('click',showRegister);$('#authRegisterCancel')?.addEventListener('click',showLogin);$('#authRegisterCreate')?.addEventListener('click',register);$('#signOutBtn')?.addEventListener('click',signOut);switchUser?.addEventListener('click',changeUser);regFile?.addEventListener('change',()=>{pendingPhoto=regFile.files?.[0]||null;if(pendingPhoto){const r=new FileReader();r.onload=()=>{regPreview.src=String(r.result);regPreview.hidden=false};r.readAsDataURL(pendingPhoto)}});loginPassword?.addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});paintRemembered();rememberMe.checked=!!remembered();autoSignIn.checked=localStorage.getItem(AUTO)==='1';
(async()=>{if(!client)return msg(loginMessage,'Servicio no disponible.','error');const {data}=await client.auth.getSession();const shouldAuto=localStorage.getItem(AUTO)==='1';if(data.session&&shouldAuto){try{await enter(data.session.user,await getProfile(data.session.user))}catch(e){msg(loginMessage,e.message,'error')}}else{shell.hidden=false;stage?.classList.add('auth-hidden');document.body.classList.add('auth-locked');showLogin()}})();
})();
