(()=>{
const $=s=>document.querySelector(s);
const cfg=window.MESSENGER_SUPABASE||{};
const shell=$('#authShell'),win=$('#authWindow'),loginView=$('#authLoginView'),registerView=$('#authRegisterView'),stage=$('.stage');
const loginEmail=$('#authEmail'),loginPassword=$('#authPassword'),loginStatus=$('#authPresence'),rememberMe=$('#authRememberMe'),rememberPassword=$('#authRememberPassword'),autoSignIn=$('#authAutoSignIn'),loginMessage=$('#authLoginMessage'),rememberedName=$('#authRememberedName'),rememberedImage=$('#authRememberedImage');
const regEmail=$('#registerEmail'),regName=$('#registerDisplayName'),regPassword=$('#registerPassword'),regConfirm=$('#registerPasswordConfirm'),regMessage=$('#registerMessage'),regPreview=$('#registerPhotoPreview'),regFile=$('#registerPhotoFile');
const REMEMBERED='messenger-revival:remembered-account',AUTO='messenger-revival:auto-sign-in';
let pendingPhoto=null,client=null,currentProfile=null;
function configured(){return !!(cfg.url&&cfg.publishableKey&&window.supabase?.createClient)}
if(configured())client=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
window.MessengerSession={client,user:null,profile:null,get userId(){return this.user?.id||'guest'},scopedKey(name){return `messenger-revival:user:${this.userId}:${name}`}};
function setBusy(v){win?.classList.toggle('busy',v)}
function message(el,text,type=''){if(!el)return;el.textContent=text;el.className='auth-status'+(type?' '+type:'')}
function remembered(){try{return JSON.parse(localStorage.getItem(REMEMBERED)||'null')}catch{return null}}
function paintRemembered(){const r=remembered();if(r){loginEmail.value=r.email||'';rememberedName.textContent=r.display_name||r.email||'';if(r.display_picture){rememberedImage.src=r.display_picture;rememberedImage.hidden=false;$('#authDefaultAvatar').hidden=true}else{rememberedImage.hidden=true;$('#authDefaultAvatar').hidden=false}}else{rememberedName.textContent='';rememberedImage.hidden=true;$('#authDefaultAvatar').hidden=false}}
function showLogin(){registerView.hidden=true;loginView.hidden=false;message(regMessage,'');paintRemembered();setTimeout(()=>loginPassword?.focus(),0)}
function showRegister(){loginView.hidden=true;registerView.hidden=false;message(loginMessage,'');setTimeout(()=>regEmail?.focus(),0)}
async function getProfile(user){if(!client||!user)return null;const {data,error}=await client.from('profiles').select('id,email,display_name,personal_message,display_picture,status').eq('id',user.id).maybeSingle();if(error)throw error;return data||{id:user.id,email:user.email,display_name:user.user_metadata?.display_name||user.email?.split('@')[0]||'Messenger User',personal_message:'',display_picture:'',status:'online'}}
function syncLegacyProfile(profile){if(!profile)return;localStorage.setItem('messenger-revival:nick',profile.display_name||'Messenger User');localStorage.setItem('messenger-revival:personal-message',profile.personal_message||'');localStorage.setItem('messenger-revival:self-status',profile.status||'online');if(profile.display_picture){localStorage.setItem('messenger-revival:custom-picture',profile.display_picture);localStorage.setItem('messenger-revival:display-picture','custom');localStorage.setItem('messenger-revival:hide-picture','0')}}
async function enterApp(user,profile){currentProfile=profile||await getProfile(user);window.MessengerSession.user=user;window.MessengerSession.profile=currentProfile;syncLegacyProfile(currentProfile);if(rememberMe.checked){localStorage.setItem(REMEMBERED,JSON.stringify({email:user.email,display_name:currentProfile.display_name,display_picture:currentProfile.display_picture||''}))}else localStorage.removeItem(REMEMBERED);localStorage.setItem(AUTO,autoSignIn.checked?'1':'0');shell.hidden=true;document.body.classList.remove('auth-locked');stage?.classList.remove('auth-hidden');window.dispatchEvent(new CustomEvent('messenger-revival:auth-ready',{detail:{user,profile:currentProfile}}))}
async function signIn(){if(!client){message(loginMessage,'La interfaz está lista, pero el proyecto Supabase todavía no está conectado.','error');return}const email=loginEmail.value.trim(),password=loginPassword.value;if(!email||!password){message(loginMessage,'Escribe tu correo y contraseña.','error');return}setBusy(true);message(loginMessage,'Iniciando sesión…');try{const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;const profile=await getProfile(data.user);await client.from('profiles').update({status:loginStatus.value,updated_at:new Date().toISOString()}).eq('id',data.user.id);profile.status=loginStatus.value;await enterApp(data.user,profile)}catch(err){message(loginMessage,err?.message||'No fue posible iniciar sesión.','error')}finally{setBusy(false)}}
async function uploadPhoto(user,file){if(!file||!client)return '';const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/display-picture.${ext}`;const {error}=await client.storage.from(cfg.displayPicturesBucket||'display-pictures').upload(path,file,{upsert:true,contentType:file.type||undefined});if(error)throw error;const {data}=client.storage.from(cfg.displayPicturesBucket||'display-pictures').getPublicUrl(path);return data.publicUrl||''}
async function register(){if(!client){message(regMessage,'El registro visual está listo, pero falta crear/conectar el proyecto Supabase.','error');return}const email=regEmail.value.trim(),name=regName.value.trim(),password=regPassword.value,confirm=regConfirm.value;if(!email||!name||!password){message(regMessage,'Completa correo, nombre y contraseña.','error');return}if(password!==confirm){message(regMessage,'Las contraseñas no coinciden.','error');return}if(password.length<8){message(regMessage,'Usa una contraseña de al menos 8 caracteres.','error');return}setBusy(true);message(regMessage,'Creando cuenta…');try{const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)throw error;if(data.session&&data.user){let photo='';if(pendingPhoto)photo=await uploadPhoto(data.user,pendingPhoto);const {error:profileError}=await client.from('profiles').update({display_name:name,display_picture:photo,updated_at:new Date().toISOString()}).eq('id',data.user.id);if(profileError)throw profileError;rememberMe.checked=true;loginEmail.value=email;loginPassword.value=password;message(regMessage,'Cuenta creada. Entrando a Messenger…','ok');await enterApp(data.user,await getProfile(data.user))}else{loginEmail.value=email;showLogin();message(loginMessage,'Cuenta creada. Revisa tu correo si Supabase solicita confirmación antes de iniciar sesión.','ok')}}catch(err){message(regMessage,err?.message||'No fue posible crear la cuenta.','error')}finally{setBusy(false)}}
async function signOut(){if(client)await client.auth.signOut();window.MessengerSession.user=null;window.MessengerSession.profile=null;stage?.classList.add('auth-hidden');document.body.classList.add('auth-locked');shell.hidden=false;loginPassword.value='';autoSignIn.checked=false;localStorage.setItem(AUTO,'0');paintRemembered();showLogin()}
window.MessengerAuth={signOut,client,get profile(){return currentProfile}};
$('#authSignIn')?.addEventListener('click',signIn);$('#authOpenRegister')?.addEventListener('click',showRegister);$('#authRegisterCancel')?.addEventListener('click',showLogin);$('#authRegisterCreate')?.addEventListener('click',register);
$('#authForgot')?.addEventListener('click',async()=>{if(!client){message(loginMessage,'Backend aún no conectado.','error');return}const email=loginEmail.value.trim();if(!email){message(loginMessage,'Escribe primero tu correo.','error');return}const {error}=await client.auth.resetPasswordForEmail(email);message(loginMessage,error?error.message:'Se envió el enlace de recuperación si la cuenta existe.',error?'error':'ok')});
$('#authServiceStatus')?.addEventListener('click',()=>message(loginMessage,configured()?'Servicio de autenticación configurado.':'Backend pendiente de conexión.',configured()?'ok':'error'));
regFile?.addEventListener('change',()=>{pendingPhoto=regFile.files?.[0]||null;if(!pendingPhoto)return;const r=new FileReader();r.onload=()=>{regPreview.src=String(r.result)};r.readAsDataURL(pendingPhoto)});
loginPassword?.addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});regConfirm?.addEventListener('keydown',e=>{if(e.key==='Enter')register()});
rememberPassword?.addEventListener('change',()=>{if(rememberPassword.checked)message(loginMessage,'Por seguridad Messenger Revival no guarda contraseñas en texto; la sesión segura reemplaza esta opción histórica.','ok')});
paintRemembered();rememberMe.checked=!!remembered();autoSignIn.checked=localStorage.getItem(AUTO)==='1';
(async()=>{if(!client){message(loginMessage,'Interfaz 2005 preparada. Falta conectar el proyecto Supabase para activar cuentas reales.','');return}const {data}=await client.auth.getSession();if(data.session&&localStorage.getItem(AUTO)==='1'){try{rememberMe.checked=true;await enterApp(data.session.user,await getProfile(data.session.user))}catch{showLogin()}}})();
})();