(()=>{
const $=s=>document.querySelector(s);let client=null,user=null,profile=null,peer=null,messages=[],channel=null,clearedAt=null,blocked=false;
const chat=$('#chatWindow'),pane=$('#messagePane'),form=$('#messageForm'),input=$('#messageInput'),title=$('#chatTitle'),info=$('#chatInfoName'),dot=$('#chatStatusDot'),avatar=$('#chatAvatar');
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__chatToast);window.__chatToast=setTimeout(()=>e.classList.remove('show'),2300)}
function safeName(n){return String(n||'file').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)||'file'}
function sameConversation(m,p=peer){if(!p||!user)return false;return (m.sender_id===user.id&&m.recipient_id===p.id)||(m.sender_id===p.id&&m.recipient_id===user.id)}
async function signed(path){if(!path)return'';const {data,error}=await client.storage.from('chat-attachments').createSignedUrl(path,3600);if(error)return'';return data?.signedUrl||''}
function metaName(m){return m.sender_id===user.id?(profile?.display_name||'Tú'):(peer?.display_name||peer?.email||'Contacto')}
async function renderOne(m){const row=document.createElement('div');row.className=`message ${m.sender_id===user.id?'mine':''}`;row.dataset.messageId=m.id;const meta=document.createElement('div');meta.className='message-meta';meta.textContent=`${metaName(m)} ... dice:`;row.appendChild(meta);
 if(m.kind==='text'||m.kind==='emoji'){const b=document.createElement('div');b.className='message-bubble';b.textContent=m.body||'';if(m.format&&typeof m.format==='object')Object.assign(b.style,m.format);row.appendChild(b)}
 else if(m.kind==='nudge'){const b=document.createElement('div');b.className='msn-system-event';b.textContent='(( Zumbido ))';row.appendChild(b)}
 else {const url=await signed(m.attachment_url);if(m.kind==='image'){const frame=document.createElement('div');frame.className='msn-photo-frame';const im=document.createElement('img');im.src=url;im.alt=m.attachment_name||'Imagen';frame.appendChild(im);row.appendChild(frame)}else if(m.kind==='audio'){const wrap=document.createElement('div');wrap.className='persistent-audio';const a=document.createElement('audio');a.controls=true;a.preload='metadata';a.src=url;const dl=document.createElement('a');dl.href=url;dl.download=m.attachment_name||'voice-clip.webm';dl.textContent='Descargar audio';wrap.append(a,dl);row.appendChild(wrap)}else{const a=document.createElement('a');a.className='persistent-file';a.href=url;a.download=m.attachment_name||'archivo';a.textContent=`📎 ${m.attachment_name||'Descargar archivo'}`;row.appendChild(a)}}
 const stamp=document.createElement('div');stamp.className='message-time';try{stamp.textContent=new Date(m.created_at).toLocaleString()}catch{}row.appendChild(stamp);return row}
async function render(){if(!pane)return;pane.innerHTML='';for(const m of messages)pane.appendChild(await renderOne(m));pane.scrollTop=pane.scrollHeight}
async function getClearState(){if(!peer)return null;const {data}=await client.from('conversation_state').select('cleared_at').eq('owner_id',user.id).eq('peer_id',peer.id).maybeSingle();return data?.cleared_at||null}
async function loadConversation(){if(!peer)return;clearedAt=await getClearState();let q=client.from('messages').select('*').or(`and(sender_id.eq.${user.id},recipient_id.eq.${peer.id}),and(sender_id.eq.${peer.id},recipient_id.eq.${user.id})`).order('created_at',{ascending:true}).limit(500);if(clearedAt)q=q.gt('created_at',clearedAt);const {data,error}=await q;if(error){toast(error.message);return}messages=data||[];await render();await markRead();await refreshUnread()}
async function markRead(){if(!peer)return;await client.rpc('mark_conversation_read',{p_peer_id:peer.id})}
async function refreshUnread(){if(!user||!client)return;const {data}=await client.from('messages').select('sender_id').eq('recipient_id',user.id).is('read_at',null);const counts={};(data||[]).forEach(x=>{counts[x.sender_id]=(counts[x.sender_id]||0)+1});window.dispatchEvent(new CustomEvent('messenger-revival:unread',{detail:counts}))}
async function isBlocked(){if(!peer||peer.id===user.id)return false;const {data}=await client.from('blocks').select('blocked_id').eq('owner_id',user.id).eq('blocked_id',peer.id).maybeSingle();blocked=!!data;window.dispatchEvent(new CustomEvent('messenger-revival:block-state',{detail:{peer_id:peer.id,blocked}}));return blocked}
async function openContact(p){if(!user||!client||!p)return;peer={...p,id:p.id||p.user_id};chat.style.display='';chat.classList.remove('window-minimized');title.textContent=p.is_self?`${profile?.display_name||'Yo'} — Mis notas`:(p.display_name||p.email||'Conversation');info.textContent=p.is_self?'Mis notas':(p.display_name||p.email||'');dot.className=`person-icon ${p.status||'offline'}`;const pic=p.is_self?(profile?.display_picture||''):p.display_picture;if(pic)avatar.innerHTML=`<img src="${pic}" alt="" style="width:100%;height:100%;object-fit:cover">`;else avatar.innerHTML='<span class="classic-avatar hero"><i></i><b></b><em></em></span>';if(input)input.placeholder=p.is_self?'Escribe una nota para ti...':'';await isBlocked();await loadConversation();input?.focus();window.MessengerWindowControls?.removeRestore?.('chatWindow')}
async function insertMessage(payload){if(!peer)return null;if(blocked&&peer.id!==user.id){toast('Desbloquea este contacto para enviar mensajes.');return null}const row={sender_id:user.id,recipient_id:peer.id,...payload};const {data,error}=await client.from('messages').insert(row).select().single();if(error){toast(error.message);return null}if(!messages.some(x=>x.id===data.id)){messages.push(data);await render()}if(peer.id===user.id)await markRead();return data}
async function sendText(text,format={}){const t=String(text||'').trim();if(!t)return null;return insertMessage({kind:'text',body:t,format})}
async function uploadAndSend(file,forcedKind){if(!peer||!file)return null;if(file.size>25*1024*1024){toast('El archivo supera el límite de 25 MB.');return null}const kind=forcedKind||(file.type.startsWith('image/')?'image':file.type.startsWith('audio/')?'audio':'file');const path=`${user.id}/${peer.id}/${crypto.randomUUID()}-${safeName(file.name||`${kind}.bin`)}`;const {error}=await client.storage.from('chat-attachments').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error){toast(error.message);return null}return insertMessage({kind,attachment_url:path,attachment_name:file.name||`${kind}-${Date.now()}`,attachment_mime:file.type||'',attachment_size:file.size||0})}
async function sendVoice(blob){const f=new File([blob],`voice-${Date.now()}.webm`,{type:blob.type||'audio/webm'});const r=await uploadAndSend(f,'audio');if(r)toast('Voice Clip enviado y guardado')}
async function sendSpecial(kind,body=''){return insertMessage({kind,body})}
async function clearConversation(){if(!peer)return;const now=new Date().toISOString();const {error}=await client.from('conversation_state').upsert({owner_id:user.id,peer_id:peer.id,cleared_at:now,updated_at:now});if(error)return toast(error.message);messages=[];clearedAt=now;await render();toast('Conversación vaciada para tu cuenta')}
async function toggleBlock(){if(!peer||peer.id===user.id)return false;if(blocked){const {error}=await client.from('blocks').delete().eq('owner_id',user.id).eq('blocked_id',peer.id);if(error){toast(error.message);return blocked}blocked=false;toast('Contacto desbloqueado')}else{const {error}=await client.from('blocks').insert({owner_id:user.id,blocked_id:peer.id});if(error){toast(error.message);return blocked}blocked=true;toast('Contacto bloqueado')}window.dispatchEvent(new CustomEvent('messenger-revival:block-state',{detail:{peer_id:peer.id,blocked}}));return blocked}
function closeConversation(){if(chat)chat.style.display='none'}
async function handleNew(m){if(!user||(m.sender_id!==user.id&&m.recipient_id!==user.id))return;if(sameConversation(m)){if(!clearedAt||new Date(m.created_at)>new Date(clearedAt)){if(!messages.some(x=>x.id===m.id)){messages.push(m);await render()}if(m.recipient_id===user.id)await markRead();if(m.kind==='nudge'&&m.sender_id!==user.id){chat?.classList.remove('nudging');void chat?.offsetWidth;chat?.classList.add('nudging')}}}else if(m.recipient_id===user.id){const {data:p}=await client.from('profiles').select('display_name,email').eq('id',m.sender_id).maybeSingle();const who=p?.display_name||p?.email||'Un contacto';toast(`${who} te envió ${m.kind==='text'?'un mensaje':m.kind==='audio'?'un audio':m.kind==='image'?'una imagen':'un archivo'}`);if('Notification'in window&&Notification.permission==='granted'){new Notification('Messenger Revival',{body:`${who} te envió un mensaje`})}document.title=`● ${who} — Messenger Revival`}await refreshUnread()}
function subscribe(){channel?.unsubscribe?.();channel=client.channel(`messenger-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},p=>handleNew(p.new)).subscribe()}
function installForm(){if(!form)return;form.onsubmit=async ev=>{ev.preventDefault();if(!peer)return toast('Abre una conversación.');const t=input.value.trim();if(!t)return;const cs=getComputedStyle(input),format={fontFamily:input.style.fontFamily||cs.fontFamily,fontSize:input.style.fontSize||cs.fontSize,color:input.style.color||cs.color,fontWeight:input.style.fontWeight||cs.fontWeight,fontStyle:input.style.fontStyle||cs.fontStyle,textDecoration:input.style.textDecoration||cs.textDecorationLine};const r=await sendText(t,format);if(r)input.value=''};input.onkeydown=ev=>{if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();form.requestSubmit()}}}
async function init(ev){user=ev?.detail?.user||window.MessengerSession?.user;profile=ev?.detail?.profile||window.MessengerSession?.profile;client=window.MessengerSession?.client;if(!user||!client)return;installForm();subscribe();await refreshUnread();document.title='Messenger Revival'}
window.addEventListener('messenger-revival:auth-ready',init);if(window.MessengerSession?.user)init();
window.MessengerApp={...(window.MessengerApp||{}),openContact};window.MessengerChat={openContact,sendText,sendFile:uploadAndSend,sendVoice,sendSpecial,clearConversation,toggleBlock,isBlocked:()=>blocked,closeConversation,getActivePeer:()=>peer,reload:loadConversation,refreshUnread};
const st=document.createElement('style');st.textContent='.message-time{font-size:9px;color:#7b8790;margin:1px 0 5px 12px}.persistent-audio{display:flex;align-items:center;gap:8px;margin:4px 0 7px 12px}.persistent-audio audio{height:30px;max-width:300px}.persistent-audio a,.persistent-file{color:#0645ad;text-decoration:underline}.persistent-file{display:inline-block;margin:5px 0 8px 12px}.msn-system-event{padding:5px 9px;color:#4b6d82;font-style:italic}';document.head.appendChild(st);
})();