(()=>{
const $=s=>document.querySelector(s);let client=null,user=null,profile=null,peer=null,messages=[],channel=null,clearedAt=null,blocked=false,renderVersion=0,reconnectTimer=null,realtimeReady=false;const seenMessageIds=new Set();
const chat=$('#chatWindow'),pane=$('#messagePane'),form=$('#messageForm'),input=$('#messageInput'),title=$('#chatTitle'),info=$('#chatInfoName'),dot=$('#chatStatusDot'),avatar=$('#chatAvatar');
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__chatToast);window.__chatToast=setTimeout(()=>e.classList.remove('show'),2300)}
function safeName(n){return String(n||'file').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)||'file'}
function sameConversation(m,p=peer){if(!p||!user)return false;return (m.sender_id===user.id&&m.recipient_id===p.id)||(m.sender_id===p.id&&m.recipient_id===user.id)}
async function signed(path){if(!path)return'';const {data,error}=await client.storage.from('chat-attachments').createSignedUrl(path,3600);if(error)return'';return data?.signedUrl||''}
function metaName(m){return m.sender_id===user.id?(profile?.display_name||'Tú'):(peer?.display_name||peer?.email||'Contacto')}
function applyDisplayNameStyle(node,p={}){if(!node)return;const f=p.display_name_font||'Tahoma',s=p.display_name_style||'normal',z=Math.min(18,Math.max(9,Number(p.display_name_size)||11)),col=/^#[0-9a-f]{6}$/i.test(p.display_name_color||'')?p.display_name_color:'#111111';node.style.fontFamily=`"${f}",Tahoma,Verdana,Arial,sans-serif`;node.style.fontWeight=s.includes('bold')?'700':'400';node.style.fontStyle=s.includes('italic')?'italic':'normal';node.style.fontSize=`${z}px`;node.style.color=col}
function compareMessages(a,b){const time=new Date(a.created_at||0)-new Date(b.created_at||0);return time||String(a.id||'').localeCompare(String(b.id||''))}
function mergeMessage(message){if(!message?.id||seenMessageIds.has(message.id))return false;seenMessageIds.add(message.id);messages.push(message);messages.sort(compareMessages);return true}
function applyMessageFormat(node,format){if(!format||typeof format!=='object')return;const safe={...format};const size=parseFloat(safe.fontSize);delete safe.fontSize;Object.assign(node.style,safe);if(Number.isFinite(size))node.style.fontSize=`${Math.min(3,Math.max(.85,size/11))}em`}
function paintConversationIdentity(){if(!peer)return;title.textContent=peer.is_self?`${profile?.display_name||'Yo'} — Mis notas`:(peer.display_name||peer.email||'Conversation');info.textContent=peer.is_self?'Mis notas':(peer.display_name||peer.email||'');if(!peer.is_self)applyDisplayNameStyle(info,peer);else info.removeAttribute('style');dot.className=`person-icon ${peer.status||'offline'}`;const pic=peer.is_self?(profile?.display_picture||''):peer.display_picture;if(pic){const im=document.createElement('img');im.className='profile-avatar-image';im.src=pic;im.alt=peer.display_name||'Display picture';avatar.replaceChildren(im)}else avatar.innerHTML='<span class="classic-avatar hero"><i></i><b></b><em></em></span>'}
function handleProfileChange(next){if(!next?.id||!user)return;if(next.id===user.id){profile={...(profile||{}),...next};if(window.MessengerSession?.profile)Object.assign(window.MessengerSession.profile,next);window.MessengerProfileSync?.paint?.(profile.display_picture||'')}if(peer?.id===next.id){peer={...peer,...next};paintConversationIdentity()}}
async function renderOne(m){const row=document.createElement('div');row.className=`message ${m.sender_id===user.id?'mine':''}`;row.dataset.messageId=m.id;const meta=document.createElement('div');meta.className='message-meta';meta.textContent=`${metaName(m)} ... dice:`;applyDisplayNameStyle(meta,m.sender_id===user.id?(profile||{}):(peer||{}));row.appendChild(meta);
 if(m.kind==='text'||m.kind==='emoji'){const b=document.createElement('div');b.className='message-bubble';b.textContent=m.body||'';applyMessageFormat(b,m.format);row.appendChild(b)}
 else if(m.kind==='nudge'){const b=document.createElement('div');b.className='msn-system-event';b.textContent='(( Zumbido ))';row.appendChild(b)}
 else {const url=await signed(m.attachment_url);if(m.kind==='image'){const frame=document.createElement('div');frame.className='msn-photo-frame';const im=document.createElement('img');im.src=url;im.alt=m.attachment_name||'Imagen';im.loading='lazy';frame.appendChild(im);row.appendChild(frame)}else if(m.kind==='audio'){const wrap=document.createElement('div');wrap.className='persistent-audio';const a=document.createElement('audio');a.controls=true;a.preload='metadata';a.src=url;const dl=document.createElement('a');dl.href=url;dl.download=m.attachment_name||'voice-clip.webm';dl.textContent='Descargar audio';wrap.append(a,dl);row.appendChild(wrap)}else{const a=document.createElement('a');a.className='persistent-file';a.href=url;a.download=m.attachment_name||'archivo';a.textContent=`📎 ${m.attachment_name||'Descargar archivo'}`;row.appendChild(a)}}
 const stamp=document.createElement('div');stamp.className='message-time';try{stamp.textContent=new Date(m.created_at).toLocaleString()}catch{}row.appendChild(stamp);return row}
async function render(){if(!pane)return;const version=++renderVersion,snapshot=[...messages].sort(compareMessages),fragment=document.createDocumentFragment();for(const m of snapshot)fragment.appendChild(await renderOne(m));if(version!==renderVersion)return;pane.replaceChildren(fragment);pane.scrollTop=pane.scrollHeight}
async function getClearState(target=peer){if(!target)return null;const {data}=await client.from('conversation_state').select('cleared_at').eq('owner_id',user.id).eq('peer_id',target.id).maybeSingle();return data?.cleared_at||null}
async function loadConversation(){if(!peer)return;const target={...peer},targetId=peer.id,nextClearedAt=await getClearState(target);let q=client.from('messages').select('*').or(`and(sender_id.eq.${user.id},recipient_id.eq.${targetId}),and(sender_id.eq.${targetId},recipient_id.eq.${user.id})`).order('created_at',{ascending:true}).limit(500);if(nextClearedAt)q=q.gt('created_at',nextClearedAt);const {data,error}=await q;if(!peer||peer.id!==targetId)return;if(error){toast(error.message);return}clearedAt=nextClearedAt;messages=(data||[]).sort(compareMessages);messages.forEach(m=>m?.id&&seenMessageIds.add(m.id));await render();await markRead();await refreshUnread()}
async function markRead(){if(!peer)return;await client.rpc('mark_conversation_read',{p_peer_id:peer.id})}
async function refreshUnread(){if(!user||!client)return;const {data}=await client.from('messages').select('sender_id').eq('recipient_id',user.id).is('read_at',null);const counts={};(data||[]).forEach(x=>{counts[x.sender_id]=(counts[x.sender_id]||0)+1});window.dispatchEvent(new CustomEvent('messenger-revival:unread',{detail:counts}))}
async function isBlocked(){if(!peer||peer.id===user.id)return false;const {data}=await client.from('blocks').select('blocked_id').eq('owner_id',user.id).eq('blocked_id',peer.id).maybeSingle();blocked=!!data;window.dispatchEvent(new CustomEvent('messenger-revival:block-state',{detail:{peer_id:peer.id,blocked}}));return blocked}
async function openContact(p){if(!user||!client||!p)return;peer={...p,id:p.id||p.user_id};chat.style.display='';chat.classList.remove('window-minimized');paintConversationIdentity();if(input)input.placeholder=p.is_self?'Escribe una nota para ti...':'';await isBlocked();await loadConversation();input?.focus();window.MessengerWindowControls?.removeRestore?.('chatWindow')}
async function insertMessage(payload){if(!peer)return null;if(blocked&&peer.id!==user.id){toast('Desbloquea este contacto para enviar mensajes.');return null}const targetId=peer.id,row={sender_id:user.id,recipient_id:targetId,...payload};const {data,error}=await client.from('messages').insert(row).select().single();if(error){toast(error.message);return null}if(peer?.id===targetId&&mergeMessage(data))await render();else if(data?.id)seenMessageIds.add(data.id);if(targetId===user.id)await markRead();return data}
async function sendText(text,format={}){const t=String(text||'').trim();if(!t)return null;return insertMessage({kind:'text',body:t,format})}
async function uploadAndSend(file,forcedKind){if(!peer||!file)return null;if(file.size>25*1024*1024){toast('El archivo supera el límite de 25 MB.');return null}const kind=forcedKind||(file.type.startsWith('image/')?'image':file.type.startsWith('audio/')?'audio':'file');const path=`${user.id}/${peer.id}/${crypto.randomUUID()}-${safeName(file.name||`${kind}.bin`)}`;const {error}=await client.storage.from('chat-attachments').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error){toast(error.message);return null}return insertMessage({kind,attachment_url:path,attachment_name:file.name||`${kind}-${Date.now()}`,attachment_mime:file.type||'',attachment_size:file.size||0})}
async function sendVoice(blob){const f=new File([blob],`voice-${Date.now()}.webm`,{type:blob.type||'audio/webm'});const r=await uploadAndSend(f,'audio');if(r)toast('Voice Clip enviado y guardado')}
async function sendSpecial(kind,body=''){return insertMessage({kind,body})}
async function clearConversation(){if(!peer)return;const now=new Date().toISOString();const {error}=await client.from('conversation_state').upsert({owner_id:user.id,peer_id:peer.id,cleared_at:now,updated_at:now});if(error)return toast(error.message);messages=[];clearedAt=now;await render();toast('Conversación vaciada para tu cuenta')}
async function toggleBlock(){if(!peer||peer.id===user.id)return false;if(blocked){const {error}=await client.from('blocks').delete().eq('owner_id',user.id).eq('blocked_id',peer.id);if(error){toast(error.message);return blocked}blocked=false;toast('Contacto desbloqueado')}else{const {error}=await client.from('blocks').insert({owner_id:user.id,blocked_id:peer.id});if(error){toast(error.message);return blocked}blocked=true;toast('Contacto bloqueado')}window.dispatchEvent(new CustomEvent('messenger-revival:block-state',{detail:{peer_id:peer.id,blocked}}));return blocked}
function closeConversation(){if(chat)chat.style.display='none'}
async function handleNew(m){if(!user||!m?.id||(m.sender_id!==user.id&&m.recipient_id!==user.id)||seenMessageIds.has(m.id))return;seenMessageIds.add(m.id);const incoming=m.recipient_id===user.id&&m.sender_id!==user.id;if(sameConversation(m)){if(!clearedAt||new Date(m.created_at)>new Date(clearedAt)){messages.push(m);messages.sort(compareMessages);await render();if(incoming)await markRead();if(incoming&&m.kind==='nudge'){chat?.classList.remove('nudging');void chat?.offsetWidth;chat?.classList.add('nudging');window.MessengerSounds?.playNudge?.()}else if(incoming)window.MessengerSounds?.playMessage?.()}}else if(incoming){if(m.kind==='nudge')window.MessengerSounds?.playNudge?.();else window.MessengerSounds?.playMessage?.();const {data:p}=await client.from('profiles').select('display_name,email').eq('id',m.sender_id).maybeSingle();const who=p?.display_name||p?.email||'Un contacto',kindLabel=m.kind==='text'?'un mensaje':m.kind==='audio'?'un audio':m.kind==='image'?'una imagen':m.kind==='nudge'?'un zumbido':'un archivo';toast(`${who} te envió ${kindLabel}`);if('Notification'in window&&Notification.permission==='granted'){new Notification('Messenger Revival',{body:`${who} te envió ${kindLabel}`})}document.title=`● ${who} — Messenger Revival`}await refreshUnread()}
function scheduleReconnect(){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>{if(client&&user&&!realtimeReady)subscribe()},1600)}
function subscribe(){const previous=channel;if(previous)client.removeChannel?.(previous);realtimeReady=false;const next=client.channel(`messenger-${user.id}-${crypto.randomUUID()}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},p=>handleNew(p.new)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'profiles'},p=>handleProfileChange(p.new));channel=next;next.subscribe(status=>{if(channel!==next)return;if(status==='SUBSCRIBED'){const wasReady=realtimeReady;realtimeReady=true;clearTimeout(reconnectTimer);if(!wasReady&&peer)loadConversation()}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){realtimeReady=false;scheduleReconnect()}})}
function installForm(){if(!form)return;form.onsubmit=async ev=>{ev.preventDefault();if(!peer)return toast('Abre una conversación.');const t=input.value.trim();if(!t)return;const cs=getComputedStyle(input),format={fontFamily:input.style.fontFamily||cs.fontFamily,fontSize:input.style.fontSize||cs.fontSize,color:input.style.color||cs.color,fontWeight:input.style.fontWeight||cs.fontWeight,fontStyle:input.style.fontStyle||cs.fontStyle,textDecoration:input.style.textDecoration||cs.textDecorationLine};const r=await sendText(t,format);if(r)input.value=''};input.onkeydown=ev=>{if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();form.requestSubmit()}}}
function cleanup(){clearTimeout(reconnectTimer);reconnectTimer=null;realtimeReady=false;if(channel&&client)client.removeChannel?.(channel);channel=null;user=null;profile=null;peer=null;messages=[];seenMessageIds.clear();renderVersion++}
async function init(ev){const nextUser=ev?.detail?.user||window.MessengerSession?.user,nextProfile=ev?.detail?.profile||window.MessengerSession?.profile,nextClient=window.MessengerSession?.client;cleanup();user=nextUser;profile=nextProfile;client=nextClient;if(!user||!client)return;installForm();subscribe();await refreshUnread();document.title='Messenger Revival'}
window.addEventListener('messenger-revival:auth-ready',init);window.addEventListener('messenger-revival:auth-signed-out',cleanup);window.addEventListener('online',()=>{if(user&&!realtimeReady)subscribe()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&user&&!realtimeReady)subscribe()});if(window.MessengerSession?.user)init();
window.MessengerApp={...(window.MessengerApp||{}),openContact};window.MessengerChat={openContact,sendText,sendFile:uploadAndSend,sendVoice,sendSpecial,clearConversation,toggleBlock,isBlocked:()=>blocked,closeConversation,getActivePeer:()=>peer,reload:loadConversation,refreshUnread};
const st=document.createElement('style');st.textContent='.message-time{font-size:clamp(10px,.45em,16px);line-height:1.35;color:#7b8790;margin:2px 0 .55em 1em}.persistent-audio{display:flex;align-items:center;gap:8px;margin:4px 0 7px 12px}.persistent-audio audio{height:30px;max-width:300px}.persistent-audio a,.persistent-file{color:#0645ad;text-decoration:underline}.persistent-file{display:inline-block;margin:5px 0 8px 12px}.msn-system-event{padding:.35em .65em;color:#4b6d82;font-style:italic}';document.head.appendChild(st);
})();
