(()=>{
const $=s=>document.querySelector(s);let installed=false,timer=null;
function scopedKey(name){const id=window.MessengerSession?.user?.id||'guest';return `messenger-revival:user:${id}:${name}`}
function rememberedUpdate(patch){try{const s=window.MessengerSession,k='messenger-revival:remembered-account',r=JSON.parse(localStorage.getItem(k)||'null');if(!r||!s?.user||String(r.email||'').toLowerCase()!==String(s.user.email||'').toLowerCase())return;localStorage.setItem(k,JSON.stringify({...r,...patch}))}catch{}}
async function save(patch){const s=window.MessengerSession,c=s?.client,u=s?.user;if(!c||!u)return false;const data={...patch,updated_at:new Date().toISOString()};const {error}=await c.from('profiles').update(data).eq('id',u.id);if(error){console.warn('Profile sync failed',error.message);return false}Object.assign(s.profile||{},patch);if(patch.display_name!==undefined)rememberedUpdate({display_name:patch.display_name});if(patch.display_picture!==undefined)rememberedUpdate({display_picture:patch.display_picture});return true}
function debounceSave(patch){clearTimeout(timer);timer=setTimeout(()=>save(patch),350)}
function paint(url){['#selfAvatar','#selfAvatarChat'].forEach(sel=>{const h=$(sel);if(h){h.innerHTML='';h.classList.toggle('has-profile-picture',!!url);if(url){h.style.width='100%';h.style.height='100%';h.style.background='none';const im=document.createElement('img');im.src=url;im.alt='Display picture';im.className='profile-avatar-image';h.appendChild(im)}else{h.style.removeProperty('width');h.style.removeProperty('height');h.style.removeProperty('background');h.innerHTML='<span class="classic-avatar self"><i></i><b></b><em></em></span>'}}})}
async function uploadFile(file){const s=window.MessengerSession,c=s?.client,u=s?.user;if(!c||!u||!file)return'';const ext=((file.type||'image/png').split('/')[1]||'png').replace('jpeg','jpg'),path=`${u.id}/display-picture-${Date.now()}.${ext}`;const {error}=await c.storage.from('display-pictures').upload(path,file,{upsert:false,contentType:file.type||'image/png'});if(error)throw error;return c.storage.from('display-pictures').getPublicUrl(path).data.publicUrl||''}
async function setDisplayPicture(source){try{let url='';if(source?.file)url=await uploadFile(source.file);else if(source?.url)url=source.url;else if(source?.number){url=new URL(`assets/display-pictures/msn-${String(source.number).padStart(2,'0')}.png`,location.href).href}else return false;if(!url)return false;const ok=await save({display_picture:url});if(!ok)return false;paint(url);localStorage.setItem(scopedKey('custom-picture'),url);localStorage.setItem(scopedKey('display-picture'),'custom');localStorage.setItem('messenger-revival:custom-picture',url);localStorage.setItem('messenger-revival:display-picture','custom');localStorage.setItem('messenger-revival:hide-picture','0');return true}catch(e){console.warn('Display Picture sync failed',e?.message||e);return false}}
async function syncDisplayPicture(){const selected=localStorage.getItem(scopedKey('display-picture'))||'default',raw=localStorage.getItem(scopedKey('custom-picture'))||'';if(selected==='custom'&&raw){if(/^https?:/i.test(raw))return setDisplayPicture({url:raw});if(raw.startsWith('data:')){const blob=await fetch(raw).then(r=>r.blob());return setDisplayPicture({file:new File([blob],`display-picture.${(blob.type.split('/')[1]||'png')}`,{type:blob.type})})}}return false}
async function reconcile(){const s=window.MessengerSession;if(!s?.user||!s?.profile)return;if(s.profile.display_picture){paint(s.profile.display_picture);localStorage.setItem(scopedKey('custom-picture'),s.profile.display_picture);localStorage.setItem(scopedKey('display-picture'),'custom');rememberedUpdate({display_picture:s.profile.display_picture});return}paint('');localStorage.removeItem(scopedKey('custom-picture'));localStorage.removeItem(scopedKey('display-picture'))}
function install(){if(!installed){installed=true;$('#displayName')?.addEventListener('change',e=>save({display_name:e.target.value.trim()||'Messenger User'}));$('#personalMessage')?.addEventListener('input',e=>debounceSave({personal_message:e.target.value.slice(0,129)}));$('#statusSelect')?.addEventListener('change',e=>save({status:e.target.value}))}reconcile()}
window.MessengerProfileSync={save,syncDisplayPicture,setDisplayPicture,uploadFile,paint};window.addEventListener('messenger-revival:auth-ready',install);window.addEventListener('messenger-revival:profile-updated',ev=>{const p=ev.detail;if(p?.id===window.MessengerSession?.user?.id){if(window.MessengerSession.profile)Object.assign(window.MessengerSession.profile,p);paint(p.display_picture||'')}});if(window.MessengerSession?.user)install();
})();
