-- Secure transient WebRTC signaling between authenticated contacts.
create table if not exists public.video_call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  signal_type text not null check (signal_type in ('invite','accept','reject','busy','cancel','offer','answer','ice','end')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  check (sender_id <> recipient_id)
);

alter table public.video_call_signals enable row level security;

drop policy if exists "video_signals_select_participants" on public.video_call_signals;
create policy "video_signals_select_participants" on public.video_call_signals
for select to authenticated
using ((select auth.uid()) in (sender_id, recipient_id));

drop policy if exists "video_signals_insert_sender" on public.video_call_signals;
create policy "video_signals_insert_sender" on public.video_call_signals
for insert to authenticated
with check ((select auth.uid()) = sender_id and public.can_send_message(sender_id, recipient_id));

drop policy if exists "video_signals_delete_participants" on public.video_call_signals;
create policy "video_signals_delete_participants" on public.video_call_signals
for delete to authenticated
using ((select auth.uid()) in (sender_id, recipient_id));

grant select, insert, delete on public.video_call_signals to authenticated;
grant usage, select on sequence public.video_call_signals_id_seq to authenticated;

create index if not exists video_call_signals_recipient_created_idx
on public.video_call_signals (recipient_id, created_at desc);
create index if not exists video_call_signals_sender_idx
on public.video_call_signals (sender_id);
create index if not exists video_call_signals_call_idx
on public.video_call_signals (call_id, created_at);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'video_call_signals'
  ) then
    alter publication supabase_realtime add table public.video_call_signals;
  end if;
end
$$;
